慢慢研究怎么编译吧

diff --git a/nginx_upstream_check_module-master/config b/nginx_upstream_check_module-master/config
--- a/nginx_upstream_check_module-master/config
+++ b/nginx_upstream_check_module-master/config
@@ -8,17 +8,17 @@ ngx_feature_deps="$ngx_addon_dir/ngx_http_upstream_check_module.h"
 ngx_check_src="$ngx_addon_dir/ngx_http_upstream_check_module.c"
 ngx_feature_test="int a;"
 . auto/feature
-
-if [ $ngx_found = yes ]; then
+echo "my log before check ngx_found variable it is $ngx_found !!!"
+# if [ $ngx_found = yes ]; then
     have=NGX_HTTP_UPSTREAM_CHECK . auto/have
     CORE_INCS="$CORE_INCS $ngx_feature_path"
     ngx_addon_name=ngx_http_upstream_check_module
     HTTP_MODULES="$HTTP_MODULES ngx_http_upstream_check_module"
     NGX_ADDON_DEPS="$NGX_ADDON_DEPS $ngx_feature_deps"
     NGX_ADDON_SRCS="$NGX_ADDON_SRCS $ngx_check_src"
-else
-    cat << END
-    $0: error: the ngx_http_upstream_check_module addon error.
-END
-    exit 1
-fi
+# else
+#     cat << END
+#     $0: error: the ngx_http_upstream_check_module addon error.
+# END
+#     exit 1
+# fi
